# PLEASE NOTE:
# This configuration file assumes you've added the `swift-styling` directory as a submodule to your repository.
repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.50.3
    hooks:
      - id: swiftlint
        stages: [push]
        args: ["--config", "swift-styling/.swiftlint.yml"]
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.50.8
    hooks:
      - id: swiftformat
        stages: [push]
        args: ["--config", "swift-styling/.swiftformat"]