repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.50.3
    hooks:
      - id: swiftlint
        stages: [push]
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.50.8
    hooks:
      - id: swiftformat
        stages: [push]