# PLEASE NOTE:
# This configuration file assumes you've added the `swiftlint-config` directory as a submodule to your repository.
repos:
-   repo: local
    hooks:
    -   id: swiftformat
        name: SwiftFormat
        description: "Check swift files for formatting issues with SwiftFormat"
        entry: /opt/homebrew/bin/mint run nicklockwood/Swiftformat --config swiftlint-config/.swiftformat
        language: system
        types: [swift]
        stages: [push]
    -   id: swiftlint
        name: SwiftLint
        description: "Check swift files for style issues with SwiftLint"
        entry: /opt/homebrew/bin/mint run realm/Swiftlint --config swiftlint-config/.swiftlint.yml
        language: system
        types: [swift]
        stages: [push]